# Generated by Django 4.2 on 2023-04-15 19:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('97e05d6f-06bb-425f-a1f1-704865ffd156'), editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('00713ea5-56fe-4388-82b2-c5fc5b928dbf'), editable=False, primary_key=True, serialize=False)),
                ('u_name', models.CharField(default='No asignado', max_length=60)),
                ('u_lastname', models.CharField(default='No asignado', max_length=60)),
                ('u_email', models.CharField(default='No asignado', max_length=60)),
                ('u_borndate', models.DateField()),
                ('u_phone', models.CharField(max_length=20, null=True)),
                ('u_lastlogin', models.DateTimeField()),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='umanage.login')),
            ],
        ),
    ]
