# Generated by Django 4.2 on 2023-04-17 20:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('umanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='id',
            field=models.UUIDField(default=uuid.UUID('336e33ef-400e-44d0-8068-ed0e23ae2ed0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fc3039d3-fd67-4850-b44d-b0cebd11a29d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
