# Generated by Django 4.2 on 2023-04-19 23:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('umanage', '0002_alter_login_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4d95b63d-4010-4826-89e5-da09c1ed25e8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5125f42f-fad0-447e-8b9f-8d1f313dacd3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
