# Generated by Django 4.2 on 2023-04-21 21:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('umanage', '0003_alter_login_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='id',
            field=models.UUIDField(default=uuid.UUID('420d02a3-9ad7-426e-8d78-fb0b867db0d6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('176b8252-873d-4558-978c-50befe5d0bdb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='credentials_user',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('3c64fbe1-ce8b-4aa5-82d2-aed2be64fc5b'), editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(default='No asignado', max_length=30, null=True)),
                ('name_credential', models.CharField(max_length=60)),
                ('pass_credential', models.CharField(max_length=100)),
                ('user_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umanage.user')),
            ],
        ),
    ]
