# Generated by Django 4.2 on 2023-04-28 17:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('umanage', '0004_alter_login_id_alter_user_id_credentials_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials_user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d2a16abf-6c3a-47d5-885f-31b1b7606b70'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='credentials_user',
            name='user_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercred', to='umanage.user'),
        ),
        migrations.AlterField(
            model_name='login',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8d86123e-9d4e-4ab9-a04c-57537bf237e2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e2acd87e-3b43-4e1f-9b3f-8cf3bb82c9d1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
